# Generated by Django 4.2.18 on 2025-01-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0004_remove_user_roles_delete_role_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
