# Generated by Django 4.2.18 on 2025-01-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
