# Generated by Django 4.2.18 on 2025-01-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0008_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
